#!/bin/bash

NAME=""

if [ "$#" -eq 0 ]; then
	exit 1
fi

if [ "$#" -ge 1 ]; then
	NAME=$1
	LEN=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 $1)
	WIDTH=$(ffprobe -v error -show_entries stream=width -of default=noprint_wrappers=1 $1 | sed 's/.*=//g')
	HEIGHT=$(ffprobe -v error -show_entries stream=height -of default=noprint_wrappers=1 $1 | sed 's/.*=//g')

	# do height automatically
	yes | ffmpeg -i $1 -filter:v "crop=$WIDTH:2:0:$(($HEIGHT-$HEIGHT/8))" tmp/out.mp4
fi

./notes $LEN

if [ -n "$NAME" ]; then
	OUT="mid/$(basename "$NAME" | cut -f1 -d '.').mid"
else
	OUT="mid/$(date +"%C.%j.%H.%M.%S").mid"
fi

./write

mv out.mid "$OUT"
